// Postgres access for the server: a single shared `pg` Pool plus a tiny
// forward-only SQL migration runner. Plain .sql files in ./migrations are the
// source of truth (0001 is generated by the Better Auth CLI; later files are
// hand-written), applied once each inside a transaction and recorded in
// `_migrations`. No DATABASE_URL means no pool is ever opened; callers must stay
// in static-only mode instead.
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Pool } from "pg";

export const databaseUrl: string = process.env.DATABASE_URL?.trim() ?? "";
export const isDatabaseConfigured: boolean = databaseUrl.length > 0;

const MIGRATION_LOCK_ID = 724_830_008;

const migrationsDir = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "migrations"
);

let pool: Pool | null = null;

/** Lazily create the shared connection pool. */
export function getPool(): Pool {
  if (!isDatabaseConfigured) {
    throw new Error(
      "DATABASE_URL is required before opening the Postgres pool"
    );
  }

  if (!pool) {
    pool = new Pool({ connectionString: databaseUrl });
  }
  return pool;
}

/**
 * Apply any not-yet-applied `.sql` files in lexical order, each in its own
 * transaction, recording successes in `_migrations`. Idempotent: re-running
 * applies nothing new. Returns the list of files applied this run.
 */
export async function runMigrations(p: Pool = getPool()): Promise<string[]> {
  const client = await p.connect();
  const ran: string[] = [];
  let lockAcquired = false;

  try {
    await client.query("select pg_advisory_lock($1)", [MIGRATION_LOCK_ID]);
    lockAcquired = true;
    await client.query(
      `create table if not exists _migrations (
         name text primary key,
         applied_at timestamptz not null default now()
       )`
    );

    const appliedRows = await client.query<{ name: string }>(
      "select name from _migrations"
    );
    const applied = new Set(appliedRows.rows.map((row) => row.name));

    const files = (await readdir(migrationsDir))
      .filter((file) => file.endsWith(".sql"))
      .sort();

    for (const file of files) {
      if (applied.has(file)) {
        continue;
      }

      const sql = await readFile(path.join(migrationsDir, file), "utf8");
      try {
        await client.query("begin");
        await client.query(sql);
        await client.query("insert into _migrations (name) values ($1)", [
          file,
        ]);
        await client.query("commit");
        ran.push(file);
      } catch (error) {
        await client.query("rollback");
        throw error;
      }
    }
  } finally {
    if (lockAcquired) {
      await client.query("select pg_advisory_unlock($1)", [MIGRATION_LOCK_ID]);
    }
    client.release();
  }

  return ran;
}
