export const incentives: string[] = [
  "amazing!",
  "awesome!",
  "marvelous!",
  "good job!",
  "great job!",
  "just in time!",
  "killed it!",
  "nailed it!",
  "nice going!",
  "outstanding!",
  "superb!",
  "that was fast!",
  "well done!",
  "well played!",
];
