export const incentives: string[] = [
  "amazing!",
  "awesome!",
  "big if true!",
  "good job!",
  "great!",
  "just in time!",
  "killed it!",
  "nailed it!",
  "nice!",
  "superb!",
  "that was fast!",
  "well done!",
  "well played!",
];
