export const placeholders: string[] = [
  "activate windows",
  "answer mom in whatsapp",
  "borrow lemon from a neighbor",
  "brew coffee",
  "buy 0.0000001 bitcoin",
  "call grandma",
  "cancel netflix account",
  "chest workout",
  "chiropractor session at 6PM",
  "clean room",
  "commit irrelevant github code",
  "configure neovim",
  "contribute to open source",
  "stretch your legs",
  "crack photoshop",
  "create spotify playlist",
  "delete tiktok",
  "drink 2L water",
  "eat pizza",
  "extend duolingo streak",
  "exterminate cordyceps",
  "format PC",
  "get toilet paper",
  "invest $10 in stocks",
  "learn to moonwalk",
  "lose a valorant ranked game",
  "make orange juice",
  "migrate to arch linux",
  "move jira card",
  "never give you up",
  "order sushi",
  "play grob opening in chess",
  "post-lunch power nap",
  "practice italian",
  "press F to pay respects",
  "purchase winrar",
  "read 10 pages of my book",
  "renew twitch prime",
  "schedule doctor appointment",
  "scroll twitter",
  "share phived",
  "skip instagram stories",
  "sleep for 7 hours",
  "study rust ownership",
  "sunbathe for vitamin D",
  "take the trash out",
  "talk to chatGPT",
  "tweet a thread",
  "uninstall league of legends",
  "upgrade node version",
  "walk for 20 minutes",
  "wash the dishes",
  "watch the office",
];
