export const placeholders: string[] = [
  "acquire the sauce",
  "finally activate windows",
  "answer mom in whatsapp",
  "borrow lemon from a neighbor",
  "brew some coffee",
  "buy 0.0000001 bitcoin",
  "call grandma @2PM",
  "cancel your netflix account",
  "a chest workout",
  "chiropractor session @6PM",
  "clean your room",
  "commit irrelevant github code",
  "configure neovim",
  "contribute to open source",
  "crack adobe photoshop",
  "create a spotify playlist",
  "delete tiktok",
  "math homework",
  "donate to adblock",
  "drink 2L water",
  "eat some pizza",
  "extend your duolingo streak",
  "exterminate cordyceps",
  "format your PC",
  "get toilet paper",
  "invest $10 in stocks",
  "learn to moonwalk",
  "lose a valorant ranked game",
  "make orange juice",
  "migrate to arch linux",
  "move jira card to done",
  "never give you up",
  "order sushi @8PM",
  "play the grob opening in chess",
  "take a post-lunch power nap",
  "practice italian",
  "press F to pay respects",
  "purchase winrar",
  "read 10 pages of your book",
  "renew your twitch prime",
  "schedule a doctor appointment",
  "scroll through twitter",
  "share phived with a friend",
  "skip instagram stories",
  "sleep for 7 hours",
  "stretch your legs",
  "study rust ownership",
  "sunbathe for vitamin D",
  "take the trash out",
  "talk to chatGPT",
  "tweet a thread @10AM",
  "uninstall league of legends",
  "upgrade your node version",
  "walk for 20 minutes",
  "wash the dishes",
  "watch the office",
];
