export const placeholders = [
  'acquire the sauce',
  'activate windows',
  'answer mom in whatsapp',
  'borrow lemon from a neighbor',
  'brew some coffee',
  'buy 0.0000001 bitcoin',
  'call grandma',
  'cancel netflix',
  'a chest workout',
  'chiropractor session',
  'clean your room',
  'commit irrelevant github code',
  'configure neovim',
  'contribute to open source',
  'crack adobe photoshop',
  'create a spotify playlist',
  'delete tiktok',
  'math homework',
  'donate to adblock',
  'drink 2L water',
  'eat some pizza',
  'extend duolingo streak',
  'exterminate cordyceps',
  'format your PC',
  'get toilet paper',
  'invest $10 in stocks',
  'ignore console warnings',
  'learn to moonwalk',
  'lose a valorant game',
  'make orange juice',
  'migrate to arch linux',
  'move jira card to done',
  'rickroll a friend',
  'order sushi @8PM',
  'play bullet in chess.com',
  'take a post-lunch power nap',
  'practice italian',
  'press F to pay respects',
  'purchase winrar',
  'read 10 pages of your book',
  'renew your twitch prime',
  'schedule a doctor appointment',
  'scroll through twitter',
  'share phived with a friend',
  'skip instagram stories',
  'sleep for 7 hours',
  'stretch your legs',
  'study rust ownership',
  'sunbathe for vitamin D',
  'take the trash out',
  'talk to chatGPT',
  'throw a party',
  'tweet a thread',
  'uninstall league of legends',
  'upgrade your node version',
  'walk for 20 minutes',
  'wash the dishes',
  'watch the office',
];
