export { appendProtocolToUrl } from "src/utils/appendProtocolToUrl";
export { extractTaskLink } from "src/utils/extractTaskLink";
export { getRandomElement } from "src/utils/getRandomElement";
export { handleSetTheme } from "src/utils/handleSetTheme";
export { isMobile } from "src/utils/isMobile";
export { isPosteriorCalendarDay } from "src/utils/isPosteriorCalendarDay";
export { isThemeSetToDark } from "src/utils/isThemeSetToDark";
export { getViewportWidth } from "src/utils/getViewportWidth";
export { isDailyPage } from "src/utils/isDailyPage";
export { reorderListFromDragResult } from "src/utils/reorderListFromDragResult";
export { setTasksDefaultWidth } from "src/utils/setTasksDefaultWidth";
export { type DefaultSvgProps } from "src/utils/defaultSvgProps";
