export const placeholders: string[] = [
  "answer mom in whatsapp",
  "activate windows",
  "borrow lemon from a neighbor",
  "brew coffee",
  "buy 0.0000001 bitcoin",
  "call grandma",
  "cancel netflix account",
  "chest workout",
  "commit irrelevant github code",
  "configure neovim",
  "contribute to open source",
  "crack photoshop",
  "create spotify playlist",
  "drink 2L water",
  "eat pizza",
  "extend duolingo streak",
  "format PC",
  "get toilet paper",
  "invest $10 in stocks",
  "learn to moonwalk",
  "lose at chess",
  "make orange juice",
  "migrate to arch linux",
  "move jira card",
  "order sushi",
  "purchase winrar",
  "practice italian",
  "renew twitch prime",
  "schedule doctor appointment",
  "scroll tiktok",
  "share phived",
  "study rust ownership",
  "sunbathe for vitamin D",
  "talk to chatGPT",
  "take a power nap",
  "tweet a thread",
  "uninstall league of legends",
  "watch the office",
  "walk for 20 minutes",
];
