export const incentives = [
  "amazing!",
  "awesome!",
  "brilliant",
  "marvelous!",
  "good job!",
  "great job!",
  "just in time!",
  "killed it!",
  "nailed it!",
  "outstanding!",
  "superb!",
  "you got there eventually",
  "that was fast!",
  "well done!",
  "well played!",
  "let's goooo!",
  "no notes.",
  "*chef's kiss*",
  "absolute unit!",
  "shipped.",
  "too easy!",
  "you're him!",
  "built different.",
  "big W!",
  "you're speedrunning!",
  "clean.",
  "that's the stuff!",
  "look at you go!",
  "effortless!",
  "smashing!",
  "cracking job!",
  "spot on!",
  "blinding!",
  "proper job!",
];
