export const placeholders = [
  "acquire the sauce",
  "activate windows",
  "answer mum text",
  "borrow lemon from a neighbor",
  "brew an espresso",
  "buy 0.0000001 bitcoin",
  "call grandma",
  "cancel netflix",
  "chest workout",
  "book chiropractor",
  "clean the room",
  "light an incense",
  "charge your airpods",
  "commit irrelevant github code",
  "record a vlog",
  "buy a diary",
  "make dinner reservations",
  "configure neovim",
  "write confluence documentation",
  "fix typo",
  "crack adobe photoshop",
  "create spotify playlist",
  "delete tiktok",
  "do math homework",
  "donate to adblock",
  "drink 2L water",
  "order more pizza",
  "extend duolingo streak",
  "exterminate cordyceps",
  "format the PC",
  "get toilet paper",
  "check robinhood portfolio",
  "ignore console warnings",
  "learn to moonwalk",
  "learn to DJ",
  "play a valorant game",
  "make orange juice",
  "migrate to arch linux",
  "move jira card to done",
  "rickroll a friend",
  "order sushi",
  "play bullet in chess.com",
  "take a post-lunch power nap",
  "practice italian",
  "press F to pay respects",
  "purchase winrar",
  "read 10 pages",
  "renew twitch prime",
  "book a gp appointment",
  "scroll x (formerly twitter)",
  "share phived with a friend",
  "skip instagram stories",
  "sleep for 7 hours",
  "stretch legs",
  "study async rust",
  "migrate to no-sql",
  "sunbathe for vitamin D",
  "throw a party",
  "post draft tweet",
  "uninstall league of legends",
  "upgrade node version",
  "go for a walk",
  "wash dishes",
  "watch the office",
  "git push --force (carefully)",
  "rm -rf node_modules",
  "rebase onto main",
  "clear chrome cache",
  "rotate aws api keys",
  "run bun update",
  "close 47 browser tabs",
  "restart mac for updates",
  "push dotfiles to github",
  "merge that stale PR",
  "mute slack for an hour",
  "enable github 2fa",
  "deploy on a friday",
  "write a single unit test",
  "pet the rubber duck",
  "ssh into the wrong server",
  "solve merge conflict",
  "rename variables",
  "git blame yourself",
  "turn the tables",
  "lock in",
  "touch grass",
  "make the bed",
  "water the plants",
  "do the laundry",
  "vacuum living room",
  "pay electric bill",
  "refill water filter",
  "take a shower",
  "floss before bed",
  "feed the cat",
  "walk the dog",
  "retweet #londonmaxxing",
  "change bedsheets",
  "buy groceries",
  "take vitamins",
  "charge iphone",
  "reply to work email",
  "return library book",
  "fold laundry",
  "empty dishwasher",
  "book a barber",
  "track amazon delivery",
  "buy birthday gift",
  "iron shirts",
  "microwave frozen lasagna",
  "sweep kitchen",
  "recycle cardboard",
  "replace dead lightbulb",
  "tidy office desk",
  "make a grocery list",
  "set alarm",
  "air out  bedroom",
  "dust the shelves",
  "clean the litter box",
  "take out the trash ",
  "clean the fridge",
  "put away the groceries",
  "clean gmail inbox",
  "backup icloud photos",
  "brew more coffee",
  "take creatine",
  "become tony soprano",
  "review pull request #67",
  "score 4 goals",
  "play sunday league",
  "watch match of the day",
  "buy christmas cards",
  "dance to disco",
  "rewatch breaking bad",
];
