export const placeholders: string[] = [
  "activate windows",
  "answer mom in whatsapp",
  "borrow lemon from a neighbor",
  "brew coffee",
  "buy 0.0000001 bitcoin",
  "call grandma",
  "cancel netflix account",
  "chest workout",
  "chiropractor session at 6PM",
  "commit irrelevant github code",
  "configure neovim",
  "contribute to open source",
  "crack photoshop",
  "create spotify playlist",
  "delete tiktok",
  "drink 2L water",
  "eat pizza",
  "extend duolingo streak",
  "format PC",
  "get toilet paper",
  "invest $10 in stocks",
  "learn to moonwalk",
  "lose at chess",
  "make orange juice",
  "migrate to arch linux",
  "move jira card",
  "never give you up",
  "order sushi",
  "practice italian",
  "press F to pay respects",
  "purchase winrar",
  "renew twitch prime",
  "schedule doctor appointment",
  "scroll twitter",
  "share phived",
  "skip instagram stories",
  "sleep for 7 hours",
  "study rust ownership",
  "sunbathe for vitamin D",
  "take a power nap",
  "talk to chatGPT",
  "tweet a thread",
  "uninstall league of legends",
  "upgrade node version",
  "walk for 20 minutes",
  "watch the office",
];
